### PR TITLE
Fix appveyor build

### PR DESCRIPTION
**Pull request by niklasf**
Using rustup to get the latest stable rust version.

There still seems to be an actual test failure remaining.

### CODE REVIEW

**Comment by antoyo** [comment]
Thanks to fix the issue.
The test is still failing on AppVeyor, but it might be becaused this specific test never worked on Windows.
I'll have to check.

**Comment by antoyo** [comment]
@niklasf [Yeah, the test never worked on Windows.](https://ci.appveyor.com/project/antoyo/futures-glib-rs/build/1.0.10)
Do you want to try to fix the TCP implementation on Windows?

Please note that it might not be worth it since `relm` will soon stop using futures (see [this branch](https://github.com/antoyo/relm/tree/fix/remove-futures)).

**Comment by niklasf** [comment]
Thanks for the heads-up. I am indeed mostly intrested in relm.

**Comment by antoyo** [comment]
So, I'll merge this PR as is.
Thanks for your contribution.

**Pull request merged**
